# Databricks notebook source
# =============================================================================
# SETUP — Creates UC catalog, schemas, tables from AML_SAR manifest
# Run once before deploying the pipeline.
# Safe to re-run — all statements use CREATE IF NOT EXISTS.
# =============================================================================

# COMMAND ----------
# Parameters (passed by workflow)
dbutils.widgets.text("catalog",     "bfsi_regulatory_catalog")
dbutils.widgets.text("report_date", "2026-03-31")

CATALOG     = dbutils.widgets.get("catalog")
REPORT_DATE = dbutils.widgets.get("report_date")
REPORT      = "AML_SAR"

print(f"Setup: {CATALOG} / {REPORT}")

# COMMAND ----------
# Catalog
spark.sql(f"CREATE CATALOG IF NOT EXISTS `{CATALOG}`"
          f" COMMENT \"Unified regulatory data catalog — AML/SAR lineage domain\"")
print(f"  catalog: {CATALOG}")

# COMMAND ----------
# Schemas
spark.sql("CREATE SCHEMA IF NOT EXISTS `{CATALOG}`.`raw_sources` COMMENT \"Unmodified ingestion from source systems\"")
print("  schema: raw_sources")
spark.sql("CREATE SCHEMA IF NOT EXISTS `{CATALOG}`.`conformed` COMMENT \"Cleansed, standardized, DQ-validated entities\"")
print("  schema: conformed")
spark.sql("CREATE SCHEMA IF NOT EXISTS `{CATALOG}`.`aml_features` COMMENT \"AML-specific behavioral and risk features\"")
print("  schema: aml_features")
spark.sql("CREATE SCHEMA IF NOT EXISTS `{CATALOG}`.`sar_reporting` COMMENT \"Final SAR submission-ready datasets\"")
print("  schema: sar_reporting")
spark.sql("CREATE SCHEMA IF NOT EXISTS `{CATALOG}`.`audit_control` COMMENT \"Lineage audit trails, DQ logs, reconciliation\"")
print("  schema: audit_control")

# COMMAND ----------
# Tables
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`raw_sources`.`core_banking_transactions` (
      `txn_id` STRING COMMENT 'Unique transaction identifier',
  `account_id` STRING COMMENT 'Account identifier — links to CRM',
  `customer_id` STRING COMMENT 'Customer identifier — PII',
  `txn_date` TIMESTAMP COMMENT 'Transaction timestamp (UTC)',
  `txn_amount` DECIMAL(18,4) COMMENT 'Transaction amount in source currency',
  `txn_currency` STRING COMMENT 'ISO 4217 currency code',
  `txn_type` STRING COMMENT 'Transaction type code (WIRE, ACH, CASH, etc.)',
  `counterparty_id` STRING COMMENT 'Counterparty identifier — PII when populated',
  `channel` STRING COMMENT 'Origination channel (branch, online, mobile)',
  `src_load_ts` TIMESTAMP COMMENT 'Source extraction timestamp'
    )
    COMMENT 'Raw transaction records from core banking — no transformations applied'
    TBLPROPERTIES ('layer'='bronze', 'regulatory'='AML_SAR', 'steward'='aml_data_team')
""")
print("  table: raw_sources.core_banking_transactions")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`raw_sources`.`crm_customer_profile` (
      `customer_id` STRING COMMENT 'Primary customer key',
  `full_name` STRING COMMENT 'Legal full name — PII',
  `date_of_birth` DATE COMMENT 'Date of birth — PII',
  `ssn_hashed` STRING COMMENT 'SHA-256 hashed SSN — PII (hashed at source)',
  `nationality` STRING COMMENT 'ISO 3166 country code',
  `risk_rating` STRING COMMENT 'KYC risk rating (LOW/MEDIUM/HIGH/PEP)',
  `kyc_review_date` DATE COMMENT 'Most recent KYC review date',
  `onboarding_date` DATE COMMENT 'Customer onboarding date',
  `src_modified_ts` TIMESTAMP COMMENT 'CRM record last modified timestamp'
    )
    COMMENT 'Customer KYC and profile data from CRM — CDC-based incremental load'
    TBLPROPERTIES ('layer'='bronze', 'regulatory'='AML_SAR', 'steward'='kyc_data_team')
""")
print("  table: raw_sources.crm_customer_profile")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`raw_sources`.`tms_alerts` (
      `alert_id` STRING COMMENT 'Unique TMS alert identifier',
  `alert_type` STRING COMMENT 'Alert scenario/typology code',
  `customer_id` STRING COMMENT 'Customer who triggered the alert',
  `alert_score` DOUBLE COMMENT 'Model-generated risk score (0-1000)',
  `alert_date` TIMESTAMP COMMENT 'Alert generation timestamp',
  `alert_status` STRING COMMENT 'Workflow status (OPEN/IN_REVIEW/CLOSED/ESCALATED)',
  `analyst_id` STRING COMMENT 'Assigned analyst ID',
  `linked_txn_ids` ARRAY<STRING> COMMENT 'Transaction IDs that triggered this alert'
    )
    COMMENT 'AML alerts generated by the transaction monitoring system'
    TBLPROPERTIES ('layer'='bronze', 'regulatory'='AML_SAR', 'steward'='aml_data_team')
""")
print("  table: raw_sources.tms_alerts")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`raw_sources`.`watchlist_screening` (
      `screening_id` STRING COMMENT 'Unique screening event ID',
  `customer_id` STRING COMMENT 'Screened customer',
  `list_name` STRING COMMENT 'Watchlist name (OFAC SDN, UN, EU, World-Check)',
  `match_status` STRING COMMENT 'Match outcome (NO_MATCH/POTENTIAL/CONFIRMED)',
  `match_score` DOUBLE COMMENT 'Fuzzy match score (0-100)',
  `screened_ts` TIMESTAMP COMMENT 'Screening timestamp'
    )
    COMMENT 'Sanctions and PEP screening results'
    TBLPROPERTIES ('layer'='bronze', 'regulatory'='AML_SAR', 'steward'='compliance_team')
""")
print("  table: raw_sources.watchlist_screening")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`conformed`.`dim_customer` (
      `customer_sk` BIGINT COMMENT 'Surrogate key',
  `customer_id` STRING COMMENT 'Natural business key',
  `full_name_masked` STRING COMMENT 'Name — masked for non-privileged access',
  `risk_rating` STRING COMMENT 'Conformed risk rating',
  `is_pep` BOOLEAN COMMENT 'PEP flag derived from screening',
  `is_sanctioned` BOOLEAN COMMENT 'Sanctions flag',
  `kyc_current` BOOLEAN COMMENT 'True if KYC review within 365 days',
  `effective_from` TIMESTAMP COMMENT 'SCD2 effective date',
  `effective_to` TIMESTAMP COMMENT 'SCD2 expiry date (NULL = current)',
  `is_current` BOOLEAN COMMENT 'SCD2 current flag'
    )
    COMMENT 'Conformed customer dimension — merged CRM + KYC + screening signals'
    TBLPROPERTIES ('layer'='silver', 'regulatory'='AML_SAR', 'steward'='aml_data_team')
""")
print("  table: conformed.dim_customer")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`conformed`.`fact_transactions` (
      `txn_sk` BIGINT COMMENT 'Surrogate key',
  `txn_id` STRING COMMENT 'Source transaction ID',
  `customer_sk` BIGINT COMMENT 'FK to dim_customer',
  `txn_date` DATE COMMENT 'Transaction date (UTC)',
  `txn_amount_usd` DECIMAL(18,4) COMMENT 'Amount normalized to USD using FX rates',
  `txn_type` STRING COMMENT 'Standardized transaction type',
  `is_cash` BOOLEAN COMMENT 'True for cash transactions (CTR threshold logic)',
  `ctr_eligible` BOOLEAN COMMENT 'True if >= $10,000 cash (CTR reportable)',
  `dq_passed` BOOLEAN COMMENT 'True if all critical DQ rules passed',
  `dq_flags` ARRAY<STRING> COMMENT 'List of failed DQ rule IDs'
    )
    COMMENT 'Cleansed and enriched transaction fact — USD-normalized, typed, DQ-passed'
    TBLPROPERTIES ('layer'='silver', 'regulatory'='AML_SAR', 'steward'='aml_data_team')
""")
print("  table: conformed.fact_transactions")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`aml_features`.`customer_txn_behavior` (
      `customer_sk` BIGINT COMMENT 'FK to dim_customer',
  `feature_date` DATE COMMENT 'Feature computation date',
  `txn_count_30d` INT COMMENT 'Transaction count — last 30 days',
  `txn_volume_usd_30d` DECIMAL(18,4) COMMENT 'Total USD volume — last 30 days',
  `txn_count_90d` INT COMMENT 'Transaction count — last 90 days',
  `txn_volume_usd_90d` DECIMAL(18,4) COMMENT 'Total USD volume — last 90 days',
  `cash_txn_count_30d` INT COMMENT 'Cash transactions — last 30 days',
  `structuring_flag` BOOLEAN COMMENT 'True if structuring pattern detected (transactions just below $10k threshold)',
  `rapid_movement_flag` BOOLEAN COMMENT 'True if funds cycle through account < 24hrs',
  `unique_counterparties_30d` INT COMMENT 'Number of distinct counterparties — last 30 days'
    )
    COMMENT 'Aggregated behavioral features per customer — 30/60/90 day windows'
    TBLPROPERTIES ('layer'='gold', 'regulatory'='AML_SAR', 'steward'='aml_model_team')
""")
print("  table: aml_features.customer_txn_behavior")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`aml_features`.`alert_enriched` (
      `alert_id` STRING COMMENT 'TMS alert ID',
  `customer_sk` BIGINT COMMENT 'FK to dim_customer',
  `alert_score` DOUBLE COMMENT 'TMS model score',
  `composite_risk_score` DOUBLE COMMENT 'Composite score (TMS + behavioral + KYC risk)',
  `is_pep` BOOLEAN COMMENT 'PEP flag at alert time',
  `is_sanctioned` BOOLEAN COMMENT 'Sanctions flag at alert time',
  `structuring_flag` BOOLEAN COMMENT 'Structuring behavior flag',
  `sar_recommended` BOOLEAN COMMENT 'System recommendation to file SAR',
  `recommendation_reason` STRING COMMENT 'Primary reason code for SAR recommendation'
    )
    COMMENT 'TMS alerts enriched with customer risk profile and behavioral features'
    TBLPROPERTIES ('layer'='gold', 'regulatory'='AML_SAR', 'steward'='aml_data_team')
""")
print("  table: aml_features.alert_enriched")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`sar_reporting`.`sar_case` (
      `sar_case_id` STRING COMMENT 'Internal SAR case identifier',
  `alert_id` STRING COMMENT 'Source alert that triggered SAR',
  `customer_sk` BIGINT COMMENT 'Subject customer',
  `sar_type` STRING COMMENT 'SAR typology code (FinCEN activity type)',
  `suspicious_activity_begin` DATE COMMENT 'Begin date of suspicious activity',
  `suspicious_activity_end` DATE COMMENT 'End date of suspicious activity',
  `total_amount_usd` DECIMAL(18,4) COMMENT 'Total USD value of suspicious activity',
  `narrative_text` STRING COMMENT 'SAR narrative — may contain PII',
  `filing_status` STRING COMMENT 'DRAFT / REVIEW / APPROVED / SUBMITTED / WITHDRAWN',
  `fincen_bsa_id` STRING COMMENT 'FinCEN BSA ID returned on submission',
  `submitted_ts` TIMESTAMP COMMENT 'FinCEN submission timestamp',
  `deadline_ts` TIMESTAMP COMMENT '30-day filing deadline from alert date'
    )
    COMMENT 'SAR case master — one record per SAR filing decision'
    TBLPROPERTIES ('layer'='gold', 'regulatory'='AML_SAR', 'steward'='compliance_team')
""")
print("  table: sar_reporting.sar_case")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`sar_reporting`.`sar_submission_payload` (
      `sar_case_id` STRING COMMENT 'FK to sar_case',
  `filing_institution` STRING COMMENT 'Institution name and LEI',
  `subject_json` STRING COMMENT 'JSON blob — SAR subject details (PII)',
  `activity_json` STRING COMMENT 'JSON blob — suspicious activity details',
  `narrative_final` STRING COMMENT 'Approved final narrative (PII)',
  `xml_payload` STRING COMMENT 'Rendered FinCEN XML — populated after approval',
  `payload_hash` STRING COMMENT 'SHA-256 hash of xml_payload for integrity',
  `generated_ts` TIMESTAMP COMMENT 'Payload generation timestamp'
    )
    COMMENT 'FinCEN Form 111 — submission-ready payload matching FinCEN XML schema'
    TBLPROPERTIES ('layer'='gold', 'regulatory'='AML_SAR', 'steward'='compliance_team')
""")
print("  table: sar_reporting.sar_submission_payload")
spark.sql("""
    CREATE TABLE IF NOT EXISTS `bfsi_regulatory_catalog`.`audit_control`.`lineage_run_log` (
      `run_id` STRING COMMENT 'Unique pipeline run ID',
  `pipeline_name` STRING COMMENT 'Pipeline identifier',
  `source_table` STRING COMMENT 'Source table FQN',
  `target_table` STRING COMMENT 'Target table FQN',
  `run_start_ts` TIMESTAMP COMMENT 'Pipeline start timestamp',
  `run_end_ts` TIMESTAMP COMMENT 'Pipeline end timestamp',
  `rows_read` BIGINT COMMENT 'Rows read from source',
  `rows_written` BIGINT COMMENT 'Rows written to target',
  `dq_pass_count` BIGINT COMMENT 'Rows passing all DQ rules',
  `dq_fail_count` BIGINT COMMENT 'Rows failing at least one DQ rule',
  `status` STRING COMMENT 'Run status (SUCCESS/FAILED/PARTIAL)'
    )
    COMMENT 'Pipeline execution audit log — every run captured for regulatory traceability'
    TBLPROPERTIES ('layer'='control', 'regulatory'='AML_SAR', 'steward'='data_governance_team')
""")
print("  table: audit_control.lineage_run_log")

# COMMAND ----------
# DQ rules stored as table properties (read by dq_runner.py at runtime)
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`raw_sources`.`core_banking_transactions` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_001", "field": "txn_id", "rule_type": "not_null", "severity": "critical", "description": "Transaction ID must never be null"}, {"rule_id": "dq_002", "field": "txn_amount", "rule_type": "not_null", "severity": "critical", "description": "Amount must not be null"}, {"rule_id": "dq_003", "field": "txn_amount", "rule_type": "range_check", "severity": "critical", "params": {"min": 0}, "description": "Amount must be non-negative"}, {"rule_id": "dq_004", "field": "txn_currency", "rule_type": "reference_check", "severity": "high", "params": {"reference_table": "audit_control.ref_iso_currency"}, "description": "Currency must be valid ISO 4217 code"}, {"rule_id": "dq_005", "field": "txn_date", "rule_type": "not_future", "severity": "high", "description": "Transaction date must not be in the future"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`raw_sources`.`crm_customer_profile` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_010", "field": "customer_id", "rule_type": "not_null", "severity": "critical", "description": "Customer ID must never be null"}, {"rule_id": "dq_011", "field": "risk_rating", "rule_type": "value_set", "severity": "critical", "params": {"allowed_values": ["LOW", "MEDIUM", "HIGH", "PEP", "BLOCKED"]}, "description": "Risk rating must be a known value"}, {"rule_id": "dq_012", "field": "kyc_review_date", "rule_type": "staleness", "severity": "high", "params": {"max_age_days": 365}, "description": "KYC review must not be older than 1 year"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`raw_sources`.`tms_alerts` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_020", "field": "alert_id", "rule_type": "not_null", "severity": "critical", "description": "Alert ID must not be null"}, {"rule_id": "dq_021", "field": "alert_score", "rule_type": "range_check", "severity": "critical", "params": {"min": 0, "max": 1000}, "description": "Alert score must be within 0-1000"}, {"rule_id": "dq_022", "field": "alert_status", "rule_type": "value_set", "severity": "high", "params": {"allowed_values": ["OPEN", "IN_REVIEW", "CLOSED", "ESCALATED", "SAR_FILED"]}, "description": "Status must be known value"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`raw_sources`.`watchlist_screening` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_030", "field": "match_status", "rule_type": "value_set", "severity": "critical", "params": {"allowed_values": ["NO_MATCH", "POTENTIAL_MATCH", "CONFIRMED_MATCH", "FALSE_POSITIVE"]}, "description": "Match status must be valid"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`conformed`.`dim_customer` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_040", "field": "risk_rating", "rule_type": "not_null", "severity": "critical", "description": "Risk rating must always be populated"}, {"rule_id": "dq_041", "field": "customer_sk", "rule_type": "unique", "severity": "critical", "description": "Surrogate key must be unique"}, {"rule_id": "dq_042", "field": "kyc_current", "rule_type": "not_null", "severity": "high", "description": "KYC currency flag must be computed"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`conformed`.`fact_transactions` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_050", "field": "txn_amount_usd", "rule_type": "not_null", "severity": "critical", "description": "USD amount must be populated after FX conversion"}, {"rule_id": "dq_051", "field": "dq_passed", "rule_type": "not_null", "severity": "critical", "description": "DQ flag must always be computed"}, {"rule_id": "dq_052", "field": "customer_sk", "rule_type": "ref_integrity", "severity": "critical", "params": {"reference_table": "conformed.dim_customer"}, "description": "Customer SK must exist in dim_customer"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`aml_features`.`customer_txn_behavior` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_060", "field": "structuring_flag", "rule_type": "not_null", "severity": "critical", "description": "Structuring flag must always be computed"}, {"rule_id": "dq_061", "field": "txn_volume_usd_30d", "rule_type": "not_null", "severity": "critical", "description": "30-day volume must not be null"}, {"rule_id": "dq_062", "field": "feature_date", "rule_type": "not_null", "severity": "critical", "description": "Feature date must be set"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`aml_features`.`alert_enriched` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_070", "field": "composite_risk_score", "rule_type": "not_null", "severity": "critical", "description": "Composite risk score must be populated"}, {"rule_id": "dq_071", "field": "sar_recommended", "rule_type": "not_null", "severity": "critical", "description": "SAR recommendation flag must always be set"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`sar_reporting`.`sar_case` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_080", "field": "filing_status", "rule_type": "value_set", "severity": "critical", "params": {"allowed_values": ["DRAFT", "REVIEW", "APPROVED", "SUBMITTED", "WITHDRAWN"]}, "description": "Filing status must be valid"}, {"rule_id": "dq_081", "field": "narrative_text", "rule_type": "not_null", "severity": "critical", "description": "SAR narrative must be present before submission"}, {"rule_id": "dq_082", "field": "total_amount_usd", "rule_type": "not_null", "severity": "critical", "description": "Total suspicious amount must be captured"}, {"rule_id": "dq_083", "field": "deadline_ts", "rule_type": "not_null", "severity": "critical", "description": "Filing deadline must always be computed"}, {"rule_id": "dq_084", "field": "suspicious_activity_begin", "rule_type": "not_null", "severity": "critical", "description": "Activity begin date required"}]')")
spark.sql("ALTER TABLE `bfsi_regulatory_catalog`.`sar_reporting`.`sar_submission_payload` SET TBLPROPERTIES ('dq_rules' = '[{"rule_id": "dq_090", "field": "payload_hash", "rule_type": "not_null", "severity": "critical", "description": "Payload hash must always be computed for integrity"}, {"rule_id": "dq_091", "field": "subject_json", "rule_type": "valid_json", "severity": "critical", "description": "Subject JSON must be parseable"}, {"rule_id": "dq_092", "field": "activity_json", "rule_type": "valid_json", "severity": "critical", "description": "Activity JSON must be parseable"}]')")

# COMMAND ----------
# Cross-schedule validations stored as catalog tag
_xval = []
print(f"  {len(_xval)} cross-schedule validations registered")

# COMMAND ----------
# Business rules summary
_brules = '["SAR must be filed within 30 days of alert date (BSA requirement)", "Cash transactions >= $10,000 must be flagged as CTR eligible", "Any customer with CONFIRMED sanctions match must be flagged before downstream processing", "KYC must be current (within 365 days) for a customer to be classified as LOW risk", "SAR narrative must be present and non-empty before filing_status = APPROVED", "Payload hash must be computed and stored for every SAR XML submission for integrity audit"]'
for _r in _brules:
    print(f"  BR: {_r}")

print("\nSetup complete.")
